
spring:
  cloud:
    gateway:
      routes:
        - id: answer-service
          uri: http://localhost:8081
          predicates:
            - Path=/answer/**
        - id: poll-service
          uri: http://localhost:8082
          predicates:
            - Path=/poll/**
        - id: question-service
          uri: http://localhost:8083
          predicates:
            - Path=/question/**
        - id: question-with-options-service
          uri: http://localhost:8084
          predicates:
            - Path=/questionWithOptions/**
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/user/**
        - id: security
          uri: http://localhost:8080
          predicates:
            - Path=/userIdFromContext/**


server:
  port: 4000

